import type { Movie } from './types';

export const movies: Movie[] = [
  { id: '1', title: 'Blade Runner 2049', year: 2017, tagline: 'Replicants have dreams too.', posterColor: 'from-slate-800 to-amber-900', crowd: ['Solo', 'Date Night'], pacing: 25, intensity: 75, cryMeter: 35, humor: 15, romance: 25, suspense: 55, genre: ['Sci-Fi', 'Drama'], theme: ['Dystopia', 'Identity Crisis'], visualStyle: ['Film Noir', 'Gritty'], soundtrack: ['Electronic', 'Minimal'], boxOffice: 260, budget: 150, rating: 8.0, hasAListCast: true, criticsVsFans: 'critics', oscarWinner: true, oscarNominee: true, runtimeMinutes: 164, directorProminence: 88 },
  { id: '2', title: 'The Big Lebowski', year: 1998, tagline: 'Times like these call for a Big Lebowski.', posterColor: 'from-amber-800 to-yellow-600', crowd: ['Group', 'Solo'], pacing: 45, intensity: 40, cryMeter: 5, humor: 85, romance: 10, suspense: 20, genre: ['Comedy', 'Crime'], theme: ['Fish out of Water', 'Noir'], visualStyle: ['Gritty', 'Symmetric'], soundtrack: ['Minimal', 'Classic Songs'], boxOffice: 18, budget: 25, rating: 8.1, hasAListCast: true, criticsVsFans: 'fans', oscarWinner: false, oscarNominee: false, runtimeMinutes: 117, directorProminence: 92 },
  { id: '3', title: 'Drive', year: 2011, tagline: 'There are no clean getaways.', posterColor: 'from-rose-900 to-cyan-900', crowd: ['Date Night', 'Solo'], pacing: 30, intensity: 65, cryMeter: 20, humor: 10, romance: 40, suspense: 75, genre: ['Crime', 'Drama'], theme: ['Revenge', 'Noir'], visualStyle: ['Film Noir', 'Symmetric'], soundtrack: ['Electronic', 'Iconic Score'], boxOffice: 76, budget: 85, rating: 7.8, hasAListCast: true, criticsVsFans: 'both', oscarWinner: false, oscarNominee: false, runtimeMinutes: 100, directorProminence: 72 },
  { id: '4', title: 'Amélie', year: 2001, tagline: 'One person can change your life forever.', posterColor: 'from-emerald-700 to-amber-500', crowd: ['Date Night', 'Solo'], pacing: 50, intensity: 35, cryMeter: 55, humor: 60, romance: 80, suspense: 15, genre: ['Romance', 'Comedy', 'Family'], theme: ['Found Family', 'Quest'], visualStyle: ['Vibrant', 'Symmetric'], soundtrack: ['Orchestral'], boxOffice: 174, budget: 10, rating: 8.3, hasAListCast: false, criticsVsFans: 'both', oscarWinner: false, oscarNominee: false, runtimeMinutes: 122, directorProminence: 78 },
  { id: '5', title: 'Mad Max: Fury Road', year: 2015, tagline: 'What a lovely day.', posterColor: 'from-orange-800 to-amber-950', crowd: ['Group', 'Solo'], pacing: 95, intensity: 90, cryMeter: 25, humor: 25, romance: 5, suspense: 88, genre: ['Action', 'Sci-Fi'], theme: ['Dystopia', 'Survival', 'Escape'], visualStyle: ['Vibrant', 'Gritty'], soundtrack: ['Electronic', 'Iconic Score'], boxOffice: 380, budget: 150, rating: 8.1, hasAListCast: true, criticsVsFans: 'both', oscarWinner: true, oscarNominee: true, runtimeMinutes: 120, directorProminence: 85 },
  { id: '6', title: 'Donnie Darko', year: 2001, tagline: 'October 2, 1988: The worst day of his life.', posterColor: 'from-violet-900 to-indigo-950', crowd: ['Solo', 'Date Night'], pacing: 40, intensity: 85, cryMeter: 60, humor: 35, romance: 30, suspense: 70, genre: ['Sci-Fi', 'Drama'], theme: ['Time Travel', 'Coming of Age', 'Twist Ending'], visualStyle: ['Film Noir', 'Gritty'], soundtrack: ['Electronic', 'Minimal'], boxOffice: 1.3, budget: 4.5, rating: 8.0, hasAListCast: false, criticsVsFans: 'fans', oscarWinner: false, oscarNominee: false, runtimeMinutes: 113, directorProminence: 65, popularity: 12, voteCount: 8500 },
  { id: '7', title: 'The Grand Budapest Hotel', year: 2014, tagline: 'A murder most foul.', posterColor: 'from-rose-600 to-pink-800', crowd: ['Date Night', 'Group'], pacing: 60, intensity: 45, cryMeter: 40, humor: 70, romance: 35, suspense: 40, genre: ['Comedy', 'Drama'], theme: ['Quest', 'Escape'], visualStyle: ['Vibrant', 'Symmetric'], soundtrack: ['Orchestral'], boxOffice: 175, budget: 25, rating: 8.1, hasAListCast: true, criticsVsFans: 'critics', oscarWinner: true, oscarNominee: true, runtimeMinutes: 99, directorProminence: 90 },
  { id: '8', title: 'Fight Club', year: 1999, tagline: 'Mischief. Mayhem. Soap.', posterColor: 'from-zinc-800 to-amber-700', crowd: ['Group', 'Solo'], pacing: 70, intensity: 88, cryMeter: 30, humor: 50, romance: 20, suspense: 75, genre: ['Drama', 'Thriller'], theme: ['Identity Crisis', 'Dysfunctional Family'], visualStyle: ['Gritty', 'Film Noir'], soundtrack: ['Rock & Guitar', 'Minimal'], boxOffice: 101, budget: 120, rating: 8.4, hasAListCast: true, criticsVsFans: 'fans', oscarWinner: false, oscarNominee: false, runtimeMinutes: 139, directorProminence: 90 },
  { id: '9', title: 'Eternal Sunshine of the Spotless Mind', year: 2004, tagline: 'Meet me in Montauk.', posterColor: 'from-cyan-800 to-blue-900', crowd: ['Date Night', 'Solo'], pacing: 35, intensity: 70, cryMeter: 85, humor: 40, romance: 90, suspense: 45, genre: ['Romance', 'Sci-Fi'], theme: ['Love Triangle', 'Identity Crisis'], visualStyle: ['Vibrant', 'Gritty'], soundtrack: ['Minimal', 'Iconic Score'], boxOffice: 72, budget: 20, rating: 8.3, hasAListCast: true, criticsVsFans: 'both', oscarWinner: true, oscarNominee: true, runtimeMinutes: 108, directorProminence: 75 },
  { id: '10', title: 'The Room', year: 2003, tagline: 'Can you really trust anyone?', posterColor: 'from-red-900 to-rose-700', crowd: ['Group'], pacing: 20, intensity: 15, cryMeter: 10, humor: 95, romance: 60, suspense: 20, genre: ['Drama'], theme: ['Betrayal', 'Dysfunctional Family'], visualStyle: ['Gritty'], soundtrack: ['Orchestral'], boxOffice: 0.001, budget: 6, rating: 8.0, hasAListCast: false, criticsVsFans: 'fans', oscarWinner: false, oscarNominee: false, runtimeMinutes: 99, directorProminence: 5, popularity: 15, voteCount: 4200 },
  { id: '11', title: 'In the Mood for Love', year: 2000, tagline: 'Feel the heat. Keep the passion.', posterColor: 'from-rose-800 to-cherry-900', crowd: ['Date Night', 'Solo'], pacing: 15, intensity: 50, cryMeter: 75, humor: 5, romance: 95, suspense: 25, genre: ['Romance', 'Drama'], theme: ['Love Triangle', 'Betrayal'], visualStyle: ['Film Noir', 'Symmetric'], soundtrack: ['Orchestral', 'Minimal'], boxOffice: 14, budget: 20, rating: 8.1, hasAListCast: false, criticsVsFans: 'critics', oscarWinner: false, oscarNominee: false, runtimeMinutes: 98, directorProminence: 82 },
  { id: '12', title: 'Dune', year: 2021, tagline: 'A myth in the making.', posterColor: 'from-amber-950 to-orange-800', crowd: ['Solo', 'Group'], pacing: 55, intensity: 80, cryMeter: 35, humor: 15, romance: 25, suspense: 70, genre: ['Sci-Fi', 'Adventure'], theme: ['Quest', 'Dystopia'], visualStyle: ['Symmetric', 'Gritty'], soundtrack: ['Orchestral', 'Minimal', 'Iconic Score'], boxOffice: 402, budget: 165, rating: 8.0, hasAListCast: true, criticsVsFans: 'both', oscarWinner: true, oscarNominee: true, runtimeMinutes: 155, directorProminence: 88 },
  { id: '13', title: 'Moonlight', year: 2016, tagline: 'This is the story of a lifetime.', posterColor: 'from-indigo-900 to-cyan-800', crowd: ['Solo', 'Date Night'], pacing: 25, intensity: 60, cryMeter: 70, humor: 20, romance: 45, suspense: 40, genre: ['Drama'], theme: ['Coming of Age', 'Identity Crisis', 'Found Family'], visualStyle: ['Film Noir', 'Gritty'], soundtrack: ['Minimal', 'Hip-Hop & R&B'], boxOffice: 65, budget: 4, rating: 7.4, hasAListCast: false, criticsVsFans: 'critics', oscarWinner: true, oscarNominee: true, runtimeMinutes: 111, directorProminence: 70 },
  { id: '14', title: 'Scott Pilgrim vs. the World', year: 2010, tagline: 'An epic of epic epicness.', posterColor: 'from-red-600 to-violet-700', crowd: ['Group', 'Date Night'], pacing: 90, intensity: 55, cryMeter: 25, humor: 80, romance: 65, suspense: 35, genre: ['Comedy', 'Action', 'Family'], theme: ['Coming of Age', 'Quest', 'Love Triangle'], visualStyle: ['Vibrant', 'Symmetric'], soundtrack: ['Rock & Guitar', 'Orchestral'], boxOffice: 48, budget: 60, rating: 7.8, hasAListCast: true, criticsVsFans: 'fans', oscarWinner: false, oscarNominee: false, runtimeMinutes: 112, directorProminence: 75 },
  { id: '15', title: 'Arrival', year: 2016, tagline: 'Why are they here?', posterColor: 'from-slate-700 to-teal-900', crowd: ['Solo', 'Date Night'], pacing: 20, intensity: 75, cryMeter: 80, humor: 10, romance: 50, suspense: 65, genre: ['Sci-Fi', 'Drama'], theme: ['Against the Clock', 'Twist Ending'], visualStyle: ['Symmetric', 'Gritty'], soundtrack: ['Minimal', 'Orchestral', 'Iconic Score'], boxOffice: 203, budget: 47, rating: 7.9, hasAListCast: true, criticsVsFans: 'critics', oscarWinner: true, oscarNominee: true, runtimeMinutes: 116, directorProminence: 88 },
  { id: '16', title: 'The Witch', year: 2015, tagline: 'A New-England folktale.', posterColor: 'from-stone-900 to-amber-950', crowd: ['Solo', 'Date Night'], pacing: 30, intensity: 72, cryMeter: 45, humor: 5, romance: 10, suspense: 85, genre: ['Horror', 'Drama'], theme: ['Survival', 'Dysfunctional Family'], visualStyle: ['Film Noir', 'Gritty'], soundtrack: ['Minimal'], boxOffice: 40, budget: 45, rating: 7.6, hasAListCast: false, criticsVsFans: 'critics', oscarWinner: false, oscarNominee: false, runtimeMinutes: 92, directorProminence: 68 },
  { id: '17', title: 'La La Land', year: 2016, tagline: 'Here\'s to the fools who dream.', posterColor: 'from-amber-500 to-rose-600', crowd: ['Date Night', 'Group'], pacing: 50, intensity: 40, cryMeter: 65, humor: 45, romance: 85, suspense: 20, genre: ['Romance', 'Comedy', 'Music'], theme: ['Quest', 'Redemption'], visualStyle: ['Vibrant', 'Symmetric'], soundtrack: ['Jazz', 'Classic Songs', 'Orchestral'], boxOffice: 446, budget: 30, rating: 8.0, hasAListCast: true, criticsVsFans: 'both', oscarWinner: false, oscarNominee: true, runtimeMinutes: 128, directorProminence: 80 },
  { id: '18', title: 'John Wick', year: 2014, tagline: 'Don\'t set off the boogeyman.', posterColor: 'from-zinc-900 to-red-900', crowd: ['Group', 'Solo'], pacing: 75, intensity: 82, cryMeter: 15, humor: 20, romance: 15, suspense: 80, genre: ['Action', 'Thriller'], theme: ['Revenge'], visualStyle: ['Film Noir', 'Gritty'], soundtrack: ['Electronic', 'Iconic Score'], boxOffice: 86, budget: 95, rating: 7.6, hasAListCast: true, criticsVsFans: 'fans', oscarWinner: false, oscarNominee: false, runtimeMinutes: 101, directorProminence: 60 },
  { id: '19', title: 'Portrait of a Lady on Fire', year: 2019, tagline: 'Don\'t regret. Remember.', posterColor: 'from-rose-900 to-amber-800', crowd: ['Date Night', 'Solo'], pacing: 18, intensity: 58, cryMeter: 88, humor: 15, romance: 90, suspense: 30, genre: ['Romance', 'Drama', 'History'], theme: ['Love Triangle', 'Based on True Story'], visualStyle: ['Symmetric', 'Vibrant'], soundtrack: ['Minimal', 'Orchestral'], boxOffice: 23, budget: 4, rating: 8.1, hasAListCast: false, criticsVsFans: 'critics', oscarWinner: false, oscarNominee: false, runtimeMinutes: 121, directorProminence: 72 },
  { id: '20', title: 'Everything Everywhere All at Once', year: 2022, tagline: 'The universe is so much bigger than you realize.', posterColor: 'from-violet-700 to-pink-600', crowd: ['Group', 'Date Night', 'Solo'], pacing: 92, intensity: 88, cryMeter: 78, humor: 70, romance: 55, suspense: 50, genre: ['Sci-Fi', 'Comedy', 'Action'], theme: ['Identity Crisis', 'Found Family', 'Multiverse'], visualStyle: ['Vibrant', 'Gritty', 'Symmetric'], soundtrack: ['Orchestral', 'Minimal'], boxOffice: 140, budget: 25, rating: 7.9, hasAListCast: true, criticsVsFans: 'both', oscarWinner: true, oscarNominee: true, runtimeMinutes: 139, directorProminence: 75 },
];
